const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    //admin


    FETCH_SONGTOPLAYLIST_START : 'FETCH_SONGTOPLAYLIST_START',
    FETCH_SONGTOPLAYLIST_SUCCESS : 'FETCH_SONGTOPLAYLIST_SUCCESS',
    FETCH_SONGTOPLAYLIST_FAILED : 'FETCH_SONGTOPLAYLIST_FAILED',




    
    FETCH_TRACK_SUCCESS : 'FETCH_TRACK_SUCCESS',
    
    FETCH_ALL_TRACK : 'FETCH_ALL_TRACK',

    

})

export default actionTypes;